# Generated by Django 4.0.6 on 2022-09-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_collection_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
